### PR TITLE
major refactor

### LINKED ISSUE #78: write to excel fails if output is not a table
# error message
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[26], line 1
----> 1 output = acro.finalise("test_results.xlsx")

File ~/GitHub/AI-SDC/ACRO/acro/acro.py:86, in ACRO.finalise(self, filename)
     84     utils.finalise_json(filename, self.results)
     85 elif extension == ".xlsx":
---> 86     utils.finalise_excel(filename, self.results)
     87 else:
     88     raise ValueError("Invalid file extension. Options: {.json, .xlsx}")

File ~/GitHub/AI-SDC/ACRO/acro/utils.py:147, in finalise_excel(filename, results)
    145 for table in output["output"]:
    146     start = 1 + writer.sheets[output_id].max_row
--> 147     table.to_excel(writer, sheet_name=output_id, startrow=start)

AttributeError: 'str' object has no attribute 'to_excel'

### to reproduce
 run test.ipynb (the one that uses the charity data)
and add a cell at the end with the command
output = acro.finalise("test_results.xlsx")

### cause
in utils.py around line 147
            for table in output["output"]:
                start = 1 + writer.sheets[output_id].max_row
                table.to_excel(writer, sheet_name=output_id, startrow=start)

### Fix
Assumption is that the output is a table, which is not always true (e.g. unsupported output)
need to test the type and the write out as appropriate if it is jsut a string

### PR DESCRIPTION
**Pull request by rpreen**
* Created record.py which contains a Record class for storing, serializing, and loading outputs.
* Added status, type and properties to the output metadata.
* Removed the timestamp from the output naming.
* Removed automatic reloading of existing results.
* Custom output filepaths are now relatve instead of absolute.
* Statsmodels outputs are split into multiple csv files instead of one.
* Output field in JSON is now a list of filepaths.
* Finalise() now takes two arguments: path and ext to specifiy a folder.
* Custom outputs are automatically copied to the outputs folder upon finalise()
* Avoids attempting to write custom outputs to excel (i.e., fixes #78)
* Timestamps are now in ISO format.
* Comments are now stored as a list of strings.

See the end of the [test notebook](https://github.com/AI-SDC/ACRO/blob/add_structured_outputs/notebooks/test.ipynb) to see what files are written and the contents of an example `results.json`

### CODE REVIEW

**Comment by rpreen** [comment]
@bloodearnest @benbc
Does the structure of the files generated and JSON output in this PR (shown in the notebook linked above) work for you? 
Is there anything obviously missing or need changing?

**Comment by bloodearnest** [comment]
Thanks @rpreen, this looks great!

The new JSON structure is much easy to consume and use, thanks.

Two minor possible suggestions:

1) multiple comments can be added to an output. Currently, these are appended to a string. Ideally they would be a list of distinct comments to help display more cleanly?

2) The timestamp format is currently non-standard. Can we suggest use ISO8601 format instead? This commonly used in JSON, and is easy to both generate and parse in python (`dt.isoformat()/dt.fromisoformat()`).

Thanks

**Comment by rpreen** [comment]
@jim-smith do we want to add a field in the JSON to report the `outcome` in terms of cell indexes for #83 or should we just replace the existing `outcome` values in the JSON where we currently write the suppression masks? The problem with writing the full masks is that there could be major bloat when dealing with very large tables so should we cease doing that now?

**Comment by benbc** [comment]
@rpreen More structured data for the `outcome` would be very welcome for us. But since this is such a big change, with so many useful things in it, we'd love to be able to integrate with it sooner rather than later. If it's possible to defer changes to the `outcome` to a later PR, that would be great.

**Comment by rpreen** [comment]
@benbc do you need it in PyPI to integrate or are you cloning the repo?

**Comment by benbc** [comment]
@bloodearnest :point_up:

**Comment by bloodearnest** [comment]
We've got a draft PR that's tracking this branch from github currently, we can consume PyPI or github for our development.

However, if users are generating their *own* outputs to test with the ACRO viewer, I imagine they'll be using the PyPI release, so would be good to keep in sync, or at least not have a lot of lag between Github and PyPI releases.

**Pull request merged**
