### PR TITLE
Adding support for R table function

### PR DESCRIPTION
**Pull request by mahaalbashir**

### CODE REVIEW

**Comment by rpreen** [comment]
I don't see why this function is necessary?

The `acro_crosstab()` R function already has the `aggfunc` as optional:

https://github.com/AI-SDC/ACRO/blob/ec7cf642f3a110a1df78bf656b1866d2a9777e78/acro.R#L6C1-L6C12

**Comment by mahaalbashir** [comment]
I think the idea is to try to add as much support as we can for the most used R functions. For crosstabulation, both `crosstab` and `table` functions are used in R

**Comment by rpreen** [comment]
But if you call `acro_crosstab(index, columns)` it should work exactly the same as the new `acro_table(index, columns)`. Unless I'm missing something, IMHO  that's just adding bloat?

**Comment by jim-smith** [comment]
bloat maybe, but small price for 'drop-in usability' for R people who know no python (ie most of them)

**Comment by mahaalbashir** [comment]
The only argument that could be passed to the crosstab function (with some tweaking) is the `dnn` argument which is (the names to be given to the dimensions in the result). The other arguments need some changes to the crosstab function

**Comment by jim-smith** [comment]
ok, thanks for looking,
How much work is the dnn one?

Suggest that for the other parameters  we provide the user with either a link to the pandas crosstab function syntax or to our docs.

@rpreen @mahaalbashir of course even if they are working remotely and also happen to have a browser open to the outside world,  they wouldn't;t be able to copy/paste a link from a 'TRE VM window' to other apps.
So may be a link is not super-helpful. 
Does help(acro_crosstab() work?

**Comment by mahaalbashir** [comment]
I have already pushed the changes with the dnn parameter included.

**Comment by rpreen** [comment]
> Does help(acro_crosstab() work?

Yes, but it would be: `help(acro.ACRO.crosstab)`

**Comment by jim-smith** [comment]
works beautifully in python -- but not at all in R.
I suspect that we definitely need to produce an R package and submit to CRAN,
question is how we prioritise that and whether it makes sense to go to the effort of doing it before we get feedback from researchers.

Is there some kind of workaround whereby in R we create a function that gets sent through to python to run help?
and if they specify params we don't know we tell them to run that command
e.g. acro_help(crosstab), acro_help(olsr), acro_help(finalise) etc?

or acro_help_crosstab() if that seems more R-like?

**Review by jim-smith — CHANGES_REQUESTED** [review]
Before we approve the PR, can you confirm that  lines 16 and 17 don't throw errors if the user does not specify dnn.

**Comment by mahaalbashir** [comment]
@jim-smith That is right. I added another parameter (`deparse.level`) ] to the function. It is also a parameter associated with the names of the rows and columns. I have updated the code and I think this also solves the problem you mentioned.

I also created the acro_help function.

**Review by jim-smith — APPROVED** [review]

**Pull request merged**
