### PR TITLE
support for multiple aggregation functions

### PR DESCRIPTION
**Pull request by rpreen**
"also fixes side issue that asking for marginal totals broke the crosstab function because the value of margins was not being passed to. the creation of the masks" - JS

### CODE REVIEW

**Review by jim-smith — APPROVED** [review]

**Comment by jim-smith** [comment]
Assume this is you finding a work-around?

**Comment by rpreen** [comment]
Yeah; should really update the `CHANGELOG.md` though...

**Comment by rpreen** [comment]
I'll try updating it

**Comment by jim-smith** [comment]
thanks

**Pull request merged**
