### PR TITLE
first implementation of crosstab and pivot_table: resolves #1 and resolves #2 and resolves #3

### LINKED ISSUE #1: Set up repo
Repo needs setting up with a development branch as default and all the relevant hooks/ci stuff for pre-commit and linting

### LINKED ISSUE #2: familiarisation with ACRO and basics of identifying primary vulnerable cells
[ESSNet_SDC_-_Guidelines_for_the_checking.pdf](https://github.com/AI-SDC/ACRO/files/9526604/ESSNet_SDC_-_Guidelines_for_the_checking.pdf)

[ACRO User Guide v01e clean.docx](https://github.com/AI-SDC/ACRO/files/9526607/ACRO.User.Guide.v01e.clean.docx)

acro user guide is most important and code is in the Eurostat repo linked from project home page

### LINKED ISSUE #3: v0.x port aCRO to python using wrapper approach for pandas
effectively create version safe pandas which just overloads the cross tab function to enforce:
- no cells with counts fewer than K
- not allowed to usemax/min as aggregation functions
- P/Q vulnerability

### PR DESCRIPTION
**Pull request by rpreen**
[Notebook](https://github.com/AI-SDC/ACRO/blob/initial-test/notebooks/test.ipynb)

### CODE REVIEW

**Comment by rpreen** [comment]
Working to a series of tests makes sense. I guess at this stage I'm slightly confused whether this project is to replicate the stata project completely, i.e., produce xls output or something slightly different? The researcher use case is a bit harder to see as well since there is more flexibility in Python - at what stage are things written as output? immediately after calling a crosstab()? For things like blocking min/max in crosstab it also doesn't seem very straightforward because the function accepts any user-defined function as input - so for the moment I just blocked all aggregation functions. The threshold rule is pretty simple to understand but some of the other rules that need to be implemented aren't very clear to me like what is P/Q vulnerability? From the user guide pdf and also from the stata code it's bit hard to interpret the rules too.

**Comment by jim-smith** [comment]
@rpreen Got to take son to to orthodontist this morning but lots of fire time this week if you want to discuss.
But here's some answers for now.


> Working to a series of tests makes sense. 

cool
>I guess at this stage I'm slightly confused whether this project is to replicate the stata project completely, i.e., produce xls output or something slightly different? 

Whatever is most portable.    If we have an 'output' function then I guess if we could have  json as the default but with the option to produce xls as well.     

> The researcher use case is a bit harder to see as well since there is more flexibility in Python - at what stage are things written as output? immediately after calling a crosstab()?

in ACRO we created a tab in the excel for each output, then the researcher said which they want to export.  (I think when they called safe finalise). Probably that is the most general, although it may produce lots of output while the user is experimenting.  
- But its likely they could use the same variable name for different tables (e.g. if they copy/paste bits of code from one notebook cell to another and just change the grouping variables) 
- so I think that within safe_crosstab() we will have to give each table a separate identifier and save a descriptor of the call params. If we keep some kind of central register then we can provide this to them for selecting which to put forward, and give that to the output checker as well

 At this stage lets write the most general, and then there needs to be some work done with researchers and output checkers around how to manage and present all the output.   I see that as very much part a of the next DARE bid.

>  For things like blocking min/max in crosstab it also doesn't seem very straightforward because the function accepts any user-defined function as input - so for the moment I just blocked all aggregation functions. 

We should check what aggregation functions stats supports, but I don't think it will be hard to find a standard list, and then block things like that for now. My suggestion would be:
- min/max (block with special message)
- mean
- median
- mode
- standard error
- standard deviation
- variance
-  skew/ kurtosis
- some standard percentiles (25.75,10,90)

After that we need talk to Felix and Lizzie about regression values.

Stata handbook is here; https://www.stata.com/manuals/rtable.pdf but we should also look at what spss/R easily support.

But the key thing here is that **we don't have to do everything**.  We looking to cover off as much of the routine stuff as possible,  and the if the researcher asks for something we don't support then they can request a manual checking.

>The threshold rule is pretty simple to understand but some of the other rules that need to be implemented aren't very clear to me like what is P/Q vulnerability? From the user guide pdf and also from the stata code it's bit hard to interpret the rules too.

nk and p/q vulnerability ar different ways of  making sure you don't release a cell where a few (usually one/two) values dominate the statistic.  There's an OECD definition here: https://stats.oecd.org/glossary/detail.asp?ID=6624

- imagine you have a two with 2 big supermarkets and a say 5 of smaller local shops.   If you release the turnover total, then one of the two big stores , knowing their turnover, can  make really good guess what the turnover of the other is (to within an upper bound based on guessing the turnover of the 5 little shops).
- if there's only one supermarket, then anyone can make a good estimate of the turnover of the supermarket.   That might tell them whether it is rising or falling, or other sensitive info

**Comment by jim-smith** [comment]
looks like to support multiple aggregation fictions we need to use a pivot table
https://stackoverflow.com/questions/65706836/how-to-use-two-different-aggregate-functions-within-crosstab-in-pandas

**Comment by jim-smith** [comment]
following on from thathlepful article, here is the one about pivot tables:
https://pbpython.com/pandas-pivot-table-explained.html

down the bottom he talks about filtering - I wonder if you could filter on count>threshold?

**Comment by jim-smith** [comment]
@rpreen I've pushed a notebook which extends yours by looking at the p% rule:
- examining one possible cell
-  creating a modified version of the table where that cell breaks the rule p<10%
-  I should have saved the modified table to use in stata 
- then creating a new aggregation function that displays that data

I guess at one level we could write a separate pytest that just checks that function by creating a 1d array of random floats, doing a version of the calculation in numpy, then casting. the array to a pandas series and passing it to the aggregation function make sure the outcomes are the same.

**Comment by jim-smith** [comment]
@rpreen just to confirm:
if tablet be produced  just displays frequency data (I.e. counts) the new don't need to do p% and nk tests for dominance, just the 'minimum contributors' threshold

If the table to be produced contains Magnitude data (I.e. the aggregation function is mean,sdev, variance, median, mode etc) then we need to do all three checks: min_contributors, p% and nk

**Pull request merged**
