### PR TITLE
handling missing values

### PR DESCRIPTION
**Pull request by mahaalbashir**

### CODE REVIEW

**Review by rpreen — CHANGES_REQUESTED** [review]
I think the default in the yaml config should be True and we need at least one test? The negative values test should be a simple template, just swap the replacement of the cell values to NaN instead of `-10` as on the line below?

https://github.com/AI-SDC/ACRO/blob/f2e57baa998365d56a17fba7fc7459f8a3e5b050/test/test_initial.py#L53

**Comment by mahaalbashir** [comment]
Having the default in the Yaml as True will change some tables in the test.ipynb and also some tests in the test_initial.py will fail because the summary will be (review; missing values found) instead of for example (fail; threshold: 6 cells suppressed; p-ratio: 1 cells suppressed). This is because the dataset has a lot of missing values (4946). That is why we thought to have the checking for missing value as False as a default and if the TRE really want to check for it then change it to True.

**Comment by rpreen** [comment]
OK, keeping it False makes sense. Still need a test though?

**Comment by rpreen** [comment]
You can try adding utils to the import at the end of this line:
https://github.com/AI-SDC/ACRO/blob/f2e57baa998365d56a17fba7fc7459f8a3e5b050/test/test_initial.py#L9

and then setting the value at the start of the test function:
https://github.com/AI-SDC/ACRO/blob/ca5ca652888ef728477c36fe52cc404ec1d4ebea/test/test_initial.py#L292
`utils.CHECK_MISSING_VALUES = True`


For some reason my system is throwing up loads of json decode errors when I try to run the tests locally, but that's probably something wrong on my end because the CI seems to be running fine...

**Review by rpreen — CHANGES_REQUESTED** [review]
Just a couple of bits to tidy in the notebook:

1) on input [9]: `utils.CHECK_MISSING_VALUES = False` needs to go in a new cell below it so that `safe_table` becomes the last line of input [9] and the notebook can render the table (and not just the INFO);

2) input [12] is the same thing as above, but also that you probably meant to reset `CHECK_MISSING_VALUES` to False

**Review by rpreen — COMMENTED** [review]
Looks good, but cells with missing values are being suppressed, which we don't do for negatives:

https://github.com/AI-SDC/ACRO/blob/af9dcdc2f94a8049e24028665746b0d4a8d14a08/acro/utils.py#L295-L300

@jim-smith do we want to actually suppress the missing cells or leave them like for negative values?

**Comment by jim-smith** [comment]
@rpreen 
>do we want to actually suppress the missing cells or leave them like for negative values?
I think that is a really good question and one to ask the TREs / WP1 people.
For now, I am content to have the functionality in there as a (non default) option and let them decide. May be on a case by case basis.

**Comment by rpreen** [comment]
We don't currently provide an option for negatives; the cells are flagged in the outcome and the summary is set to "review" but no cells are actually suppressed. 

So do we want to make this PR for missing values the same as that and then have a new PR which makes it an option for both? If so, then this PR needs to modify `apply_suppression()` to make it handle missing values the same as negatives?

**Review by rpreen — APPROVED** [review]

**Pull request merged**
