### PR TITLE
fixes problems with nan called in masks addressing issue 62

### PR DESCRIPTION
**Pull request by jim-smith**
Adds try-except around the call to filter using a mask  in method apply_suppression line 307 in utils.py

But principally adds some code in acro,crosstab lines 276-280 to convert empty/nan cells in masks to 1 (suppress) then converts whole mask to bools manually.

Possibly a neater way of doing this?

### CODE REVIEW

**Comment by rpreen** [comment]
I just added a new test for the TypeError, which works fine.

But, I'm getting this nasty JSONDecodeError when I run the tests locally - also now seeing it on the CI, which seems to be first triggered from the `test_missing()` - I was seeing this problem before in a prior PR and it seemed to be due to the reopening of outputs and was passing the tests after clearing out the outputs folder, which actually seems a bit of a bad fix anyway... if you try rerunning the tests multiple times it triggers too

**Comment by rpreen** [comment]
It's a very weird error, because as you can see when I just forced the CI to rerun the tests it now passes. However, it's still failing for me locally, so something is wrong.

**Comment by jim-smith** [comment]
Weird,
wonder if it relates to the fix that maha has jsut done/is about to do for the safemodels wrapper code 
- there she was going to reimport the json data from file, add the output, then rewind the file rot posting her and write the combined outputs to it.
-

**Comment by rpreen** [comment]
I think it was introduced when first appending to the results file instead of writing it new.

I noted it back in this PR: https://github.com/AI-SDC/ACRO/pull/60

I believe it originates from this line:
https://github.com/AI-SDC/ACRO/blob/be0fae3489f15b019641a20ca1b848e6c44ba6ad/acro/utils.py#L104

```
====================================================================================== FAILURES =======================================================================================
____________________________________________________________________________________ test_missing _____________________________________________________________________________________

data =        charity grant_type  index  year  inc_activity  inc_grants  ...  sh_assets_balance  sh_income_assets  sh_staff_a...0.391120          0.203788         3.242479               0.062849               0.308406  4.0

[918 rows x 44 columns]
acro = <acro.acro.ACRO object at 0x7f2d347d6a70>

    def test_missing(data, acro):
        """Pivot table and Crosstab with negative values."""
        utils.CHECK_MISSING_VALUES = True
        data.loc[0:10, "inc_grants"] = np.NaN
        _ = acro.crosstab(
            data.year, data.grant_type, values=data.inc_grants, aggfunc="mean"
        )
        _ = acro.pivot_table(
            data, index=["grant_type"], values=["inc_grants"], aggfunc=["mean", "std"]
        )
>       output: dict = acro.finalise()

test/test_initial.py:297: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
acro/acro.py:84: in finalise
    utils.finalise_json(filename, self.results)
acro/utils.py:104: in finalise_json
    data = json.load(file)
/usr/lib/python3.10/json/__init__.py:293: in load
    return loads(fp.read(),
/usr/lib/python3.10/json/__init__.py:346: in loads
    return _default_decoder.decode(s)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <json.decoder.JSONDecoder object at 0x7f2d7d3ca6e0>
s = '{\n    "output_0_2023-04-26-22524609": {\n        "command": "_ = acro.crosstab(data.year, data.grant_type)",\n      ...puts/output_0_2023-04-26-22524680.csv",\n        "timestamp": "2023-04-26-22524680",\n        "comments": ""\n    }\n}'
_w = <built-in method match of re.Pattern object at 0x7f2d7d3a4860>

    def decode(self, s, _w=WHITESPACE.match):
        """Return the Python representation of ``s`` (a ``str`` instance
        containing a JSON document).
    
        """
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        end = _w(s, end).end()
        if end != len(s):
>           raise JSONDecodeError("Extra data", s, end)
E           json.decoder.JSONDecodeError: Extra data: line 146 column 2 (char 11586)

/usr/lib/python3.10/json/decoder.py:340: JSONDecodeError
```

**Comment by rpreen** [comment]
If you re-run `pytest .` a second time locally then all the tests fail because of the decode error - unless deleting the outputs folder and then it just fails on that one test... but its all the same problem

**Review by rpreen — APPROVED** [review]

**Comment by jim-smith** [comment]
ir does look as thought it is something to do with the code that looks for an existing json file and if it exists:
- uses json.load to load it into a python dict called 'data'
- calls data.update() fgiving it t he new output to add
- rewinds the file pointer to position 0
- then uses json .dumps() to write it back to that file

I can't see off the top of may head whyat the problem is with that,
but this link in geeksforgeeks: https://www.geeksforgeeks.org/append-to-json-file-using-python/
uses append*() rather than update() to change the dict.

**Comment by jim-smith** [comment]
I don;t get a problem when I run pytest repeatedly on a Mac without doing anything to the outputs folder
python version 3.10.6

**Comment by rpreen** [comment]
It's definitely botched the results.json on my machine:

This is my file after running the tests (with a clean outputs folder) -- see the very end of the file

https://gist.github.com/rpreen/2fc9c4a6350b14e26f91587d19fe0a80

**Comment by rpreen** [comment]
So, if I comment out the `test_custom_output()` I can re-run pytest multiple times and it never fails, so it would seem like the problem originates in the custom output function

**Pull request merged**
